### ISSUE TITLE
largeMessageMode="FIFO" is failing

### ISSUE THREAD

**Issue by RajeshCoast** [avioconsulting/log4j2-sqs-appender#14]
Dear Sir,

I am using this log4j2-sqs-appender. we have the requirement to send large message to elastic more than 1MB. When I am using FIFO, getting the following exception.
ERROR 2023-02-07 14:16:08,152 [Log4j2-TF-8-AsyncLoggerConfig-5] [processor: ; event: ] com.avioconsulting.log4j.sqs.SqsManager: Failed to send message to SQS
java.lang.NullPointerException: null
	at com.avioconsulting.log4j.sqs.SqsManager.send(SqsManager.java:93) [log4j2-sqs-appender-1.1.0.jar:?]
	at com.avioconsulting.log4j.sqs.SqsAppender.append(SqsAppender.java:179) [log4j2-sqs-appender-1.1.0.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.callAppenders(AsyncLoggerConfig.java:126) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.log(AsyncLoggerConfig.java:120) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.logToAsyncLoggerConfigsOnCurrentThread(AsyncLoggerConfig.java:168) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:112) [log4j-core-2.17.1.jar:2.17.1]
	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:98) [log4j-core-2.17.1.jar:2.17.1]
	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [disruptor-3.4.2.jar:?]
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [disruptor-3.4.2.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

Please suggest.

Regards

**Comment by neckron** [comment]
Will fixed in the next release.
